version: "3.8"

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: "visualizer"
    env_file:
      - ../envs/common-visualizer.env
    ports:
      - 8152:8050
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "5m" # file size
