version: "3.8"

services:
  redis_db:
    image: "redis:alpine"
    ports:
      - 6379:6379
    container_name: redis_db
    command: redis-server
    volumes:
      - ./redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "5m" # file size
